name: build

env:
  PROJECT_NAME: hello_css343

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GCC
        run: sudo apt install gcc g++ cmake ninja-build clang-tidy valgrind
      - name: Run CMake
        run: cmake -GNinja -S . -B build
      - name: Build
        run: ninja -C build
      - name: Run Tests
        run: ctest
        working-directory: build
      - name: Valgrind Main
        run: valgrind --leak-check=full build/${{ env.PROJECT_NAME }}
      - name: Valgrind Tests
        run: valgrind --leak-check=full build/${{ env.PROJECT_NAME }}Test
